package: multipledispatch
platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
engine:
  - python=2.6
  - python=2.7
  - python=3.3
  - python=3.4
script:
  - touch build.sh
  - conda build .
build_targets:
  files: conda
  channels: main
