repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
        args:
          - --target-version=py38
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          # NOTE: autoupdate does not pick up flake8-bugbear since it is a transitive
          #  dependency. Make sure to update flake8-bugbear manually on a regular basis.
          - flake8-bugbear==22.8.23
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      -   id: codespell
          types_or: [rst, markdown]
          files: docs
